CREATE TABLE IF NOT EXISTS maintentry (
    id INTEGER PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    place VARCHAR(100) NOT NULL,
    cost INTEGER NOT NULL,
    mialadge INTEGER NOT NULL,
    text TEXT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);